// Auto-generated by scripts/update-models.js
// Last updated: 2026-05-27

export const MODEL_MAPPING = {
    "cognitivecomputations/dolphin-mistral-24b-venice-edition:free": {
        role: "Lightweight",
        role_de: "Leichtgewicht",
        context: "33k",
        desc_en: "Lightweight model via OpenRouter free tier.",
        desc_de: "Leichtgewicht-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.0%",
        latency: "1.7s",
        status: "online"
    },
    "deepseek/deepseek-v4-flash:free": {
        role: "Reasoning",
        role_de: "Logik",
        context: "1049k",
        desc_en: "Reasoning model via OpenRouter free tier.",
        desc_de: "Logik-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.3%",
        latency: "1.4s",
        status: "online"
    },
    "google/gemma-4-26b-a4b-it:free": {
        role: "Lightweight",
        role_de: "Leichtgewicht",
        context: "262k",
        desc_en: "Lightweight model via OpenRouter free tier.",
        desc_de: "Leichtgewicht-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.8%",
        latency: "2.6s",
        status: "online"
    },
    "google/gemma-4-31b-it:free": {
        role: "Lightweight",
        role_de: "Leichtgewicht",
        context: "262k",
        desc_en: "Lightweight model via OpenRouter free tier.",
        desc_de: "Leichtgewicht-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.3%",
        latency: "0.3s",
        status: "online"
    },
    "liquid/lfm-2.5-1.2b-instruct:free": {
        role: "Assistant",
        role_de: "Assistent",
        context: "33k",
        desc_en: "Assistant model via OpenRouter free tier.",
        desc_de: "Assistent-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.2%",
        latency: "0.8s",
        status: "online"
    },
    "liquid/lfm-2.5-1.2b-thinking:free": {
        role: "General",
        role_de: "Allgemein",
        context: "33k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.8%",
        latency: "1.7s",
        status: "online"
    },
    "meta-llama/llama-3.2-3b-instruct:free": {
        role: "Assistant",
        role_de: "Assistent",
        context: "131k",
        desc_en: "Assistant model via OpenRouter free tier.",
        desc_de: "Assistent-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.5%",
        latency: "1.5s",
        status: "online"
    },
    "meta-llama/llama-3.3-70b-instruct:free": {
        role: "Assistant",
        role_de: "Assistent",
        context: "131k",
        desc_en: "Assistant model via OpenRouter free tier.",
        desc_de: "Assistent-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.6%",
        latency: "1.4s",
        status: "online"
    },
    "minimax/minimax-m2.5:free": {
        role: "General",
        role_de: "Allgemein",
        context: "205k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.9%",
        latency: "1.4s",
        status: "online"
    },
    "nousresearch/hermes-3-llama-3.1-405b:free": {
        role: "Assistant",
        role_de: "Assistent",
        context: "131k",
        desc_en: "Assistant model via OpenRouter free tier.",
        desc_de: "Assistent-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.9%",
        latency: "2.6s",
        status: "online"
    },
    "nvidia/nemotron-3-nano-30b-a3b:free": {
        role: "General",
        role_de: "Allgemein",
        context: "256k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.3%",
        latency: "2.2s",
        status: "online"
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": {
        role: "Reasoning",
        role_de: "Logik",
        context: "256k",
        desc_en: "Reasoning model via OpenRouter free tier.",
        desc_de: "Logik-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.2%",
        latency: "2.3s",
        status: "online"
    },
    "nvidia/nemotron-3-super-120b-a12b:free": {
        role: "General",
        role_de: "Allgemein",
        context: "1000k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.1%",
        latency: "1.7s",
        status: "online"
    },
    "nvidia/nemotron-nano-12b-v2-vl:free": {
        role: "General",
        role_de: "Allgemein",
        context: "128k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.5%",
        latency: "1.2s",
        status: "degraded"
    },
    "nvidia/nemotron-nano-9b-v2:free": {
        role: "General",
        role_de: "Allgemein",
        context: "128k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.2%",
        latency: "0.9s",
        status: "online"
    },
    "openai/gpt-oss-120b:free": {
        role: "General",
        role_de: "Allgemein",
        context: "131k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.2%",
        latency: "1.7s",
        status: "online"
    },
    "openai/gpt-oss-20b:free": {
        role: "General",
        role_de: "Allgemein",
        context: "131k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.3%",
        latency: "2.6s",
        status: "online"
    },
    "poolside/laguna-m.1:free": {
        role: "General",
        role_de: "Allgemein",
        context: "262k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.1%",
        latency: "1.4s",
        status: "online"
    },
    "poolside/laguna-xs.2:free": {
        role: "General",
        role_de: "Allgemein",
        context: "262k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.5%",
        latency: "1.6s",
        status: "online"
    },
    "qwen/qwen3-coder:free": {
        role: "Code Generation",
        role_de: "Code-Generierung",
        context: "1049k",
        desc_en: "Code Generation model via OpenRouter free tier.",
        desc_de: "Code-Generierung-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.3%",
        latency: "0.3s",
        status: "online"
    },
    "qwen/qwen3-next-80b-a3b-instruct:free": {
        role: "Assistant",
        role_de: "Assistent",
        context: "262k",
        desc_en: "Assistant model via OpenRouter free tier.",
        desc_de: "Assistent-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.5%",
        latency: "1.0s",
        status: "online"
    },
    "z-ai/glm-4.5-air:free": {
        role: "General",
        role_de: "Allgemein",
        context: "131k",
        desc_en: "General model via OpenRouter free tier.",
        desc_de: "Allgemein-Modell über OpenRouter kostenlos.",
        languages: ["python","javascript","typescript","go"],
        uptime: "99.8%",
        latency: "2.3s",
        status: "online"
    }
};
