// Run daily at 00:01 UTC via GitHub Actions.
// Fetches :free models from OpenRouter API and updates mapping.js

import fs from 'fs';

const MAPPING_PATH = 'src/js/mapping.js';
const OPENROUTER_API = 'https://openrouter.ai/api/v1/models';

async function fetchFreeModels() {
    const res = await fetch(OPENROUTER_API);
    if (!res.ok) throw new Error(`API error: ${res.status}`);
    const data = await res.json();
    
    const freeModels = data.data
        .filter(m => m.id.endsWith(':free'))
        .map(m => ({
            id: m.id,
            name: m.name || m.id,
            context: m.context_length || null,
            pricing: m.pricing || {}
        }))
        .sort((a, b) => a.id.localeCompare(b.id));
    
    return freeModels;
}

function categorize(id, name) {
    const lower = (id + ' ' + name).toLowerCase();
    if (lower.includes('coder') || lower.includes('code')) {
        return { role: 'Code Generation', role_de: 'Code-Generierung' };
    }
    if (lower.includes('reason') || lower.includes('deepseek')) {
        return { role: 'Reasoning', role_de: 'Logik' };
    }
    if (lower.includes('chat') || lower.includes('instruct') || lower.includes('hermes')) {
        return { role: 'Assistant', role_de: 'Assistent' };
    }
    if (lower.includes('llama') || lower.includes('gemma') || lower.includes('phi')) {
        return { role: 'Lightweight', role_de: 'Leichtgewicht' };
    }
    return { role: 'General', role_de: 'Allgemein' };
}

function guessLanguages(id, name) {
    const langs = ['python', 'javascript', 'typescript', 'go', 'rust', 'java'];
    const lower = (id + ' ' + name).toLowerCase();
    const matched = langs.filter(l => !lower.includes('php'));
    return matched.slice(0, 4);
}

function readExistingModelIds(content) {
    const ids = [...content.matchAll(/"([^"]+:free)"/g)].map(m => m[1]);
    return new Set(ids);
}

function buildMappingContent(freeModels, existingIds) {
    const withNew = freeModels.map(m => ({
        ...m,
        isNew: !existingIds.has(m.id)
    }));
    
    withNew.sort((a, b) => {
        if (a.isNew !== b.isNew) return a.isNew ? -1 : 1;
        return a.id.localeCompare(b.id);
    });
    
    let out = 'export const MODEL_MAPPING = {\n';
    withNew.forEach((m, i) => {
        const cat = categorize(m.id, m.name);
        const langs = guessLanguages(m.id, m.name);
        const ctxStr = m.context ? (m.context < 1000 ? `${m.context}` : `${Math.round(m.context/1000)}k`) : '?';
        
        out += '    "' + m.id + '": {\n';
        out += '        role: "' + cat.role + '",\n';
        out += '        role_de: "' + cat.role_de + '",\n';
        out += '        context: "' + ctxStr + '",\n';
        out += '        desc_en: "' + cat.role + ' model via OpenRouter free tier.",\n';
        out += '        desc_de: "' + cat.role_de + '-Modell \u00fcber OpenRouter kostenlos.",\n';
        out += '        languages: ' + JSON.stringify(langs) + (m.isNew ? ',\n        new: true' : '') + '\n';
        out += '    }' + (i < withNew.length - 1 ? ',' : '') + '\n';
    });
    out += '};\n';
    return out;
}

async function main() {
    console.log('Fetching free models from OpenRouter...');
    const freeModels = await fetchFreeModels();
    console.log('Found ' + freeModels.length + ' free models');
    
    let existingContent = '';
    try {
        existingContent = fs.readFileSync(MAPPING_PATH, 'utf-8');
    } catch {
        existingContent = '';
    }
    
    const existingIds = readExistingModelIds(existingContent);
    const newIds = new Set(freeModels.map(m => m.id));
    
    // Detect added and removed models
    const added = [...newIds].filter(id => !existingIds.has(id)).sort();
    const removed = [...existingIds].filter(id => !newIds.has(id)).sort();
    
    if (added.length > 0 || removed.length > 0) {
        let msg = '';
        if (added.length > 0) {
            msg += '## Hinzugefügt\n' + added.map(id => '- ' + id).join('\n') + '\n';
        }
        if (removed.length > 0) {
            msg += '## Entfernt\n' + removed.map(id => '- ' + id).join('\n') + '\n';
        }
        // Write diff to file for the workflow to read
        fs.writeFileSync('model-changes.txt', msg);
        console.log('Model changes detected:\n' + msg);
    } else {
        console.log('No model changes detected.');
        // Remove stale diff file if it exists
        try { fs.unlinkSync('model-changes.txt'); } catch {}
    }
    
    const today = new Date().toISOString().split('T')[0];
    const header = '// Auto-generated by scripts/update-models.js\n// Last updated: ' + today + '\n\n';
    const newMapping = buildMappingContent(freeModels, existingIds);
    
    // Preserve everything after MODEL_MAPPING (getBestModels, MODEL_HISTORY)
    const restMatch = existingContent.match(/\nexport function getBestModels/);
    const rest = restMatch ? existingContent.slice(restMatch.index) : '';
    
    fs.writeFileSync(MAPPING_PATH, header + newMapping + rest);
    console.log('Updated ' + MAPPING_PATH);
}

main().catch(err => {
    console.error('Update failed:', err.message);
    process.exit(1);
});
